---
- name: Patch Windows
  hosts: windows
  vars: 
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_winrm_scheme: http
    ansible_winrm_transport: ntlm
    ansible_user: ansible
    ansible_password: ubuntuftw


  tasks:
  - name: Install all security, critical, and rollup updates without a scheduled task
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups

  - name: Hello WORLD POWERSHELL
    ansible.windows.win_powershell:
      script: Write-Host "Hello World"
    register: output

...
  
